apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: enRsbm91YXE=
  CLOUDINARY_KEY: NDc5ODk2NjM4NDYzOTg3
  CLOUDINARY_SECRET: Tm1pSWpuY3V6ZE9ZTlpyX2Z0QUROS2RGSTNV
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhR0Z5YzJocGRHaGhNak1pTENKaElqb2lZMjExWjNWeFpXcGhNSEExZGpKNGNucGhlSFZ3YVRsck5pSjkubWZfOHZqOWVsODRJNnBMVDB4R3Ntdw==
  DB_URL: bW9uZ29kYitzcnY6Ly9oYXJzaGl0aGFyZWRkeTQ2M19kYl91c2VyOlNnQzV3OUVySVV3ZmRXa1lAY2x1c3RlcjAuejQxdGNkMy5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
